language: csharp
solution: source/WindowsSpotlightWallpaper.sln
addons:
  sonarcloud:
    organization: "raulsebastian-github"
    token:
      secure: "YUHjIIaHzm13csUjw+kxq3w5uVy3thULCoyu/kUENAWM6qamOV1KDhIEM5pCTAMJN/T3tkY1QWtZh/E7q1fTZsaDEWIYtNG0W9WbtA1tzqL7W0wSXrz9gGe+7pvs0/U0kR7opUeWy2I3EFiRqBCZxk/WNHEP9GiQNId4XHlOUh837DDxfcUyMkKgCVIOFzQHSWqOvFqKajJ7SDBchLBXXuoDeL8yBTgAsfnvjh6lAQE8HHrR3OPGh+0LxP+k4ukGtcynuwJLJaFbyeXf1q5Mgauw6aFBiMlmVtMdbP+JLzvdWTIP8PdS4SSBGdJstuk12y8Gx8CywsoFHVVlXBcXVjogyr5PZwxWX34W7XMQKnENwr+8gMVoa6Tozy/L+wYlphHGJuawWg65wYxCsynjMthirfB072f6EOLXMuOKK1S30lnamfJQI5mF/G9QEXwN5ly550qHCSp9RSWtsA6U5bWNKI26mhPhZ3kL6cbh7kgJjEvu7SERYRSFrdA5caDeX7XEG2MCjaI6iiV6ys1x1IULlMpsLWsAhYnGaAKI3I9Bo/y/6XEjCUG0qZUYHRyPsj/fiW5Cyb5Qd7lhxykCGmBzh91Mc7G8/oUZmOnzItMjoa0oGDdqETGr4g9EBkxciKnXll84tLNh1rRO666cYJANw0xV4VQ7F9TRAzVM9tU="
script:
  - sonar-scanner